### ISSUE TITLE
Twin Bridge Castle - Normal Exit access_rules are blank

### ISSUE THREAD

**Issue by kngrace** [PoryGone/SMW_AP_Tracker#1]
Hi,

I'm new to playing SMW randomizer but I just arrived at Ludwig's Castle (aka Twin Bridges Castle) with level randomizer turned on and appear to be unable to reach the end despite the tracker indicating I can. I went ahead and pulled up the locations/twin_bridges/twin_bridges_castle.json file and it appears the access_rules array is blank. I believe that mario_climb is a requirement to reach the end. There may be others/alternatives. 

Would you please review what requirements are needed for the level and update accordingly? Thanks! :)

**Comment by kngrace** [comment]
I did a little more digging in ArchipelagoMW code repository for the logic rules and they have twin_bridges_castle defined as requiring mario_run and mario_climb to reach the exit. So that is what should be added. 

Source: [https://github.com/ArchipelagoMW/Archipelago/blob/main/worlds/smw/Regions.py](https://github.com/ArchipelagoMW/Archipelago/blob/main/worlds/smw/Regions.py)

Lines 954-956 read:
```
   connect(world, player, names, LocationName.twin_bridges_castle_region, LocationName.twin_bridges_castle,
            lambda state: (state.has(ItemName.mario_run, player) and
                           state.has(ItemName.mario_climb, player)))
```

**Comment by PoryGone** [comment]
Noted
