### ISSUE TITLE
Chocolate Island 4 - Dragon Coins Rules

### ISSUE THREAD

**Issue by LudwigVonKoopa87** [PoryGone/SMW_AP_Tracker#3]
```
add_location_to_region(world, player, active_locations, LocationName.chocolate_island_4_region, LocationName.chocolate_island_4_dragon,
                               lambda state: (state.has(ItemName.p_switch, player) and
                                              state.has(ItemName.progressive_powerup, player, 3)))
```

This does not seem to work. I don't have P-Switch and it appears to be reachable. 
![ci4](https://github.com/PoryGone/SMW_AP_Tracker/assets/122737479/3e80844e-ac8a-4692-a632-dc88b4dd1df7)

**Comment by PoryGone** [comment]
This is already fixed in the complete overhaul of the tracker which will be accompanying the release of v2.0.0.
