### ISSUE TITLE
Star Road 4 Secret Exit

### ISSUE THREAD

**Issue by fizzmaister** [PoryGone/SMW_AP_Tracker#5]
The Star Road 4 secret exit can be won with just feather and carry. Nothing else is needed.

However, you may want to make this a yellow, because you need to make a blind jump,

**Comment by fizzmaister** [comment]
Vanilla Secret 1 secret exit should also be yellow with just feather and climb (requires a tricky trampoline jump to make it to the secret pipe.

**Comment by PoryGone** [comment]
Please do not make issues on this repo for things that you think should be yellow. Share that with lx5 in the SMW channel on the Discord.
